defmodule Y2022.Day23Test do
  use ExUnit.Case, async: true
  alias Y2022.Day23
  doctest Day23

  test "verification, part 1", do: assert(Day23.part1_verify() == 3788)
  # test "verification, part 2", do: assert(Day23.part2_verify() == "update or delete me")

  @sample_small """
  .....
  ..##.
  ..#..
  .....
  ..##.
  .....
  """

  @sample_large """
  ..............
  ..............
  .......#......
  .....###.#....
  ...#...#.#....
  ....#...##....
  ...#.###......
  ...##.#.##....
  ....#..#......
  ..............
  ..............
  ..............
  """

  test "part1/1" do
    assert 5 == Day23.parse_input(@sample_small) |> Day23.part1(1)
    assert 15 == Day23.parse_input(@sample_small) |> Day23.part1(2)
    assert 25 == Day23.parse_input(@sample_small) |> Day23.part1(3)
    assert 110 == Day23.parse_input(@sample_large) |> Day23.part1(10)
  end

  test "parse_input/1" do
    expected = MapSet.new([{2, 3}, {2, 4}, {3, 3}, {5, 3}, {5, 4}])
    assert expected == Day23.parse_input(@sample_small)
  end
end
